# Generated by Django 4.2.23 on 2025-07-30 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textpair',
            name='session_id',
            field=models.CharField(db_index=True, default='unknown', max_length=36),
        ),
    ]
