# Generated by Django 4.2.23 on 2025-08-01 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_sessionrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionrecord',
            name='summary',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
